/* =====================================================================
 * 历史图谱数据集 v1
 * 结构说明：
 *  - civilizations：文明/地区分组（泳道）
 *  - items：条目数组，type = "event" | "person"
 *    - start/end：年份（公元前为负数，如 -221 = 公元前221年）
 *    - factions：所属文明（多值，用于同期对照）
 *    - same_period：手工标注的同期对照提示
 *  - eras：时代快捷导航
 * ===================================================================== */

const ERAS = [
  { id: "neolithic", name: "上古·文明曙光", range: [-3500, -500], desc: "文字发明，早期国家，轴心时代前夜" },
  { id: "axial", name: "轴心时代", range: [-800, -200], desc: "孔子、佛陀、苏格拉底，大思想家的世纪" },
  { id: "empire", name: "帝国时代", range: [-200, 200], desc: "汉与罗马，东西两极" },
  { id: "middle1", name: "中古早期", range: [200, 700], desc: "罗马陷落，三国两晋，拜占庭兴起" },
  { id: "middle2", name: "中古盛期", range: [700, 1100], desc: "盛唐气象，阿拉伯黄金时代" },
  { id: "middle3", name: "中古晚期", range: [1100, 1500], desc: "宋元科技、十字军、蒙古风暴" },
  { id: "earlymod", name: "大航海与变革", range: [1500, 1700], desc: "明与地理大发现，文艺复兴与科学革命" },
  { id: "enlight", name: "革命世纪", range: [1700, 1850], desc: "康乾、启蒙、独立革命、工业革命" },
  { id: "modern", name: "近代危机", range: [1850, 1950], desc: "殖民扩张、两次大战、民族觉醒" },
  { id: "contemp", name: "当代", range: [1950, 2000], desc: "冷战、去殖民化、全球化" },
];

const CIVILIZATIONS = [
  { id: "china", name: "中国", color: "#c0392b", lane: 0, desc: "从夏商周到明清，延续至今的文明" },
  { id: "westasia", name: "西亚·北非", color: "#b8860b", lane: 1, desc: "两河、埃及、波斯、阿拉伯" },
  { id: "europe", name: "欧洲", color: "#2e6da4", lane: 2, desc: "希腊、罗马、中世纪、近代西方" },
  { id: "india", name: "南亚", color: "#6a4c93", lane: 3, desc: "印度河文明、孔雀王朝、莫卧儿" },
  { id: "steppe", name: "草原·内亚", color: "#7f8c8d", lane: 4, desc: "匈奴、突厥、蒙古等游牧帝国" },
  { id: "americas", name: "美洲", color: "#2e8b57", lane: 5, desc: "玛雅、阿兹特克、印加、北美" },
  { id: "eastasia", name: "东亚其他", color: "#c96a1e", lane: 6, desc: "日本、朝鲜、越南" },
  { id: "africa", name: "撒哈拉以南非洲", color: "#8d6e63", lane: 7, desc: "库施、加纳、马里、桑海" },
];

const ITEMS = [
  /* ===== 上古·文明曙光 ===== */
  { type: "event", name: "苏美尔楔形文字", start: -3200, end: -3200, factions: ["westasia"],
    detail: "两河南部苏美尔人发明楔形文字并使用泥板书写，是目前已知最早的文字系统之一，人类进入有文字记载的历史。乌鲁克城邦人口达数万，是当时世界最大城市。",
    same_period: ["约同期：尼罗河畔上、下埃及走向统一的前夜；中国尚处新石器晚期（良渚、龙山文化）"], links: [] },
  { type: "event", name: "古埃及统一（第一王朝）", start: -3100, end: -3100, factions: ["westasia"],
    detail: "传说中美尼斯统一上、下埃及，建立第一王朝，古埃及进入法老时代。此后象形文字、纸草、历法相继成熟。",
    same_period: ["约同期：苏美尔城邦竞逐；中国龙山文化筑城盛行"], links: [] },
  { type: "event", name: "印度河文明（哈拉帕）", start: -2600, end: -1900, factions: ["india"],
    detail: "哈拉帕与摩亨佐-达罗为代表的城市文明，城市规划整齐，有下水道与标准度量衡；文字至今未被破译。约公元前1900年后衰落。",
    same_period: ["同期：埃及古王国金字塔时代；中国传说时代的黄帝、尧舜禹故事正对应这一时期"], links: [] },
  { type: "event", name: "金字塔时代（埃及古王国）", start: -2580, end: -2180, factions: ["westasia"],
    detail: "胡夫大金字塔（约前2560年）建成，埃及进入统一王权鼎盛期，行政、历法、医学高度发展。",
    same_period: ["同期：印度河文明繁荣；两河阿卡德帝国（约前2334年）建立"], links: [] },
  { type: "event", name: "阿卡德帝国", start: -2334, end: -2154, factions: ["westasia"],
    detail: "萨尔贡一世建立人类历史上第一个帝国，统一两河南部，通行阿卡德语。",
    same_period: ["同期：中国龙山时代；埃及第六王朝走向衰弱"], links: [] },
  { type: "event", name: "汉谟拉比与《汉谟拉比法典》", start: -1754, end: -1754, factions: ["westasia"],
    detail: "古巴比伦国王汉谟拉比颁布成文法典，282条刻于石柱，是最完整的早期成文法。",
    same_period: ["约同期：夏朝晚期（二里头文化鼎盛期）；喜克索斯人入侵埃及"], links: [] },
  { type: "event", name: "商汤灭夏，商朝建立", start: -1600, end: -1046, factions: ["china"],
    detail: "商汤灭夏桀建立商朝，以甲骨文和青铜器著称，是目前有直接文字证据的中国最早王朝。盘庚迁殷（约前1300年）后政局稳定。",
    same_period: ["同期：埃及新王国（图特摩斯、拉美西斯二世）；赫梯帝国崛起；雅利安人进入印度"], links: ["妇好", "拉美西斯二世"] },
  { type: "person", name: "图特摩斯三世", start: -1479, end: -1425, factions: ["westasia"],
    detail: "古埃及新王国法老，十七次远征叙利亚-巴勒斯坦，建立埃及帝国，被称「古埃及的拿破仑」。",
    same_period: ["同期：商朝（盘庚迁殷前后、妇好随武丁征战）；赫梯与米坦尼争霸"], links: ["妇好"] },
  { type: "person", name: "妇好", start: -1250, end: -1200, factions: ["china"],
    detail: "商王武丁之妻，中国历史有文字记载的第一位女将军，率军征伐羌方、土方；其墓1976年发掘，出土随葬品1900余件。",
    same_period: ["同期：埃及法老拉美西斯二世在位（前1279–前1213）；赫梯帝国与埃及争霸，卡迭石之战（约前1274）"], links: ["商汤灭夏，商朝建立"] },
  { type: "person", name: "拉美西斯二世", start: -1279, end: -1213, factions: ["westasia"],
    detail: "古埃及新王国鼎盛期法老，与赫梯签订已知最早的国际和约（卡迭石和约），大兴土木，阿布辛贝神庙是其代表。",
    same_period: ["同期：商朝武丁盛世，妇好征战；特洛伊战争传说时代（约前1250）"], links: ["妇好"] },
  { type: "event", name: "西周建立（牧野之战）", start: -1046, end: -771, factions: ["china"],
    detail: "周武王牧野之战灭商，推行分封制与宗法制；周公制礼作乐，奠定此后三千年中国政治文化基本框架。前771年犬戎攻破镐京，西周亡。",
    same_period: ["同期：大卫、所罗门王国的以色列联合王国鼎盛；亚述帝国扩张；希腊多里安人进入铁器时代"], links: ["孔子"] },
  { type: "person", name: "大卫", start: -1010, end: -970, factions: ["westasia"],
    detail: "以色列联合王国国王，定都耶路撒冷，其子所罗门建第一圣殿。《大卫》《诗篇》传统与之相关。",
    same_period: ["同期：西周初期分封诸侯；亚述帝国南下逼近黎凡特"], links: [] },
  { type: "event", name: "亚述帝国鼎盛", start: -900, end: -612, factions: ["westasia"],
    detail: "铁器武装的军事帝国，控制整个新月沃地，前722年灭以色列王国。前612年被新巴比伦与米底联军攻破尼尼微而亡。",
    same_period: ["同期：春秋诸侯争霸开始；埃及后期王朝艰难自保"], links: [] },
  { type: "event", name: "巴比伦之囚", start: -597, end: -538, factions: ["westasia"],
    detail: "新巴比伦王尼布甲尼撒二世攻陷耶路撒冷，掳走犹太精英。犹太教在此期间成型，前538年波斯居鲁士释囚。",
    same_period: ["同期：孔子约前551年出生；雅典梭伦改革（前594）"], links: ["孔子"] },

  /* ===== 轴心时代 ===== */
  { type: "event", name: "春秋时期（诸侯争霸）", start: -770, end: -476, factions: ["china"],
    detail: "周室东迁洛邑，王权衰落，齐桓晋文等「春秋五霸」相继主导。铁器牛耕推广，百家争鸣前夜。",
    same_period: ["同期：亚述帝国与巴比伦称霸西亚；罗马建城（传说前753）；希腊城邦形成"], links: ["孔子", "居鲁士大帝"] },
  { type: "person", name: "孔子", start: -551, end: -479, factions: ["china"],
    detail: "儒家创始人。删述六经、有教无类，其思想经弟子整理成《论语》，成为此后两千年中华文明的主干。",
    same_period: ["同期（佛陀约前563–前483）：释迦牟尼在印度传法；波斯居鲁士建立帝国；雅典梭伦改革"], links: ["释迦牟尼", "春秋时期（诸侯争霸）", "苏格拉底"] },
  { type: "person", name: "释迦牟尼", start: -563, end: -483, factions: ["india"],
    detail: "佛教创始人。恒河流域说法四十余年，反对种姓束缚，主张四谛八正道。",
    same_period: ["同期：孔子在中国活动；波斯帝国扩张至印度河流域"], links: ["孔子"] },
  { type: "person", name: "居鲁士大帝", start: -600, end: -530, factions: ["westasia"],
    detail: "波斯阿契美尼德王朝建立者，前539年灭新巴比伦，颁布《居鲁士圆柱》被视为最早的人权宣言之一。",
    same_period: ["同期：孔子在世；罗马共和国即将建立（前509）"], links: ["孔子", "巴比伦之囚"] },
  { type: "event", name: "波斯帝国（阿契美尼德）", start: -550, end: -330, factions: ["westasia"],
    detail: "第一个横跨欧亚非的帝国，行省制、驿道、宽容宗教政策。前490年马拉松之战、前480年萨拉米斯海战与希腊对峙。",
    same_period: ["同期：战国初期；印度摩揭陀崛起"], links: ["希波战争", "亚历山大东征"] },
  { type: "event", name: "希波战争", start: -499, end: -449, factions: ["europe", "westasia"],
    detail: "希腊城邦联军抗击波斯入侵，马拉松（前490）、温泉关与萨拉米斯（前480）诸战役，雅典海上霸权由此确立。",
    same_period: ["同期：中国春秋末年，勾践灭吴（前473）；波斯宫闱政变频仍"], links: ["孔子", "波斯帝国（阿契美尼德）"] },
  { type: "person", name: "苏格拉底", start: -469, end: -399, factions: ["europe"],
    detail: "雅典哲学家，「认识你自己」，以问答法探究伦理与知识，被判死刑饮鸩而亡，其思想由柏拉图继承。",
    same_period: ["同期：墨子（约前468–前376）在中国主张兼爱非攻；战国初年魏国李悝变法"], links: ["孔子", "柏拉图"] },
  { type: "person", name: "柏拉图", start: -427, end: -347, factions: ["europe"],
    detail: "苏格拉底弟子，创办学园（Academy），著《理想国》，理念论奠定西方哲学传统。",
    same_period: ["同期：战国中期，商鞅变法（前356）使秦国崛起；印度难陀王朝统一恒河"], links: ["苏格拉底", "亚里士多德", "商鞅变法"] },
  { type: "person", name: "亚里士多德", start: -384, end: -322, factions: ["europe"],
    detail: "柏拉图弟子、亚历山大大帝之师。百科全书式学者，逻辑学、物理学、伦理学、政治学奠基人。",
    same_period: ["同期：孟子（约前372–前289）游说诸侯；印度难陀王朝被孔雀王朝取代"], links: ["柏拉图", "亚历山大东征", "孟子"] },
  { type: "event", name: "商鞅变法", start: -356, end: -338, factions: ["china"],
    detail: "秦孝公任用商鞅两次变法：废井田、行郡县、军功爵、连坐法，秦国从此崛起为战国最强，为统一奠基。商鞅本人被车裂。",
    same_period: ["同期：柏拉图晚年办学园；波斯艺术薛西斯三世重新征服埃及"], links: ["秦始皇统一中国", "柏拉图"] },
  { type: "event", name: "亚历山大东征", start: -334, end: -323, factions: ["europe", "westasia", "india"],
    detail: "马其顿国王十年间灭波斯帝国，兵锋至印度河，建立横跨欧亚的帝国。死后帝国三分，开启希腊化时代。",
    same_period: ["同期：中国战国中晚期，屈原在世（约前340–前278）"], links: ["亚里士多德", "屈原"] },
  { type: "person", name: "屈原", start: -340, end: -278, factions: ["china"],
    detail: "楚国诗人、政治家，中国浪漫主义文学之祖，代表作《离骚》。主张联齐抗秦不被采纳，郢都陷落后自沉汨罗江。",
    same_period: ["同期：亚历山大死后部将塞琉古占据西亚，孔雀王朝旃陀罗笈多夺取印度西北部"], links: ["亚历山大东征"] },
  { type: "event", name: "孔雀王朝", start: -322, end: -185, factions: ["india"],
    detail: "旃陀罗笈多建，阿育王（约前268–前232在位）统一次大陆大部，弘扬佛教，石柱法诏传世。",
    same_period: ["同期：战国末期至秦；罗马与迦太基布匿战争"], links: ["秦始皇统一中国", "阿育王"] },
  { type: "person", name: "阿育王", start: -304, end: -232, factions: ["india"],
    detail: "孔雀王朝最著名君主，经历残酷征伐后皈依佛教，派僧团四处弘法，佛教由此成为世界性宗教。",
    same_period: ["同期：秦统一前后；第一次布匿战争（前264–前241）"], links: ["孔雀王朝", "秦始皇统一中国"] },
  { type: "event", name: "布匿战争", start: -264, end: -146, factions: ["europe", "africa"],
    detail: "罗马与迦太基三次战争。汉尼拔翻越阿尔卑斯（前218）一度震撼罗马，最终罗马毁灭迦太基，称霸西地中海。",
    same_period: ["同期：秦灭六国、楚汉相争、文景之治相继"], links: ["汉尼拔", "秦始皇统一中国"] },
  { type: "person", name: "汉尼拔", start: -247, end: -183, factions: ["africa", "europe"],
    detail: "迦太基名将，第二次布匿战争中率军翻越阿尔卑斯入侵意大利，坎尼之战歼灭罗马主力，最终败于西庇阿。",
    same_period: ["同期：秦始皇统一中国（前221）、项羽刘邦楚汉相争"], links: ["布匿战争", "秦始皇统一中国"] },

  /* ===== 帝国时代 ===== */
  { type: "event", name: "秦始皇统一中国", start: -221, end: -207, factions: ["china"],
    detail: "秦王嬴政灭六国，称始皇帝：书同文、车同轨、统一度量衡、修驰道、筑长城。前209年陈胜吴广起义，前207年秦亡，但郡县制与大一统框架延续两千年。",
    same_period: ["同期：第二次布匿战争正酣（汉尼拔在意大利）；罗马共和国即将称霸地中海"], links: ["汉武帝", "汉尼拔", "商鞅变法"] },
  { type: "event", name: "汉朝建立与文景之治", start: -202, end: -141, factions: ["china"],
    detail: "刘邦建汉后休养生息，文帝景帝轻徭薄赋，国力恢复，为汉武帝的开拓积蓄力量。",
    same_period: ["同期：罗马毁灭迦太基（前146）、征服希腊（前146）——两大强国几乎同步崛起"], links: ["汉武帝"] },
  { type: "person", name: "汉武帝", start: -156, end: -87, factions: ["china"],
    detail: "在位五十四年：罢黜百家独尊儒术、开西域、北击匈奴、通西南夷，派张骞凿空西域，丝绸之路由此贯通。",
    same_period: ["同期：罗马共和国晚期，格拉古兄弟改革（前133起）、马略军事改革"], links: ["张骞通西域", "秦始皇统一中国"] },
  { type: "event", name: "张骞通西域", start: -138, end: -119, factions: ["china", "steppe"],
    detail: "张骞两次出使西域，虽未达成军事联盟，但打通了长安至中亚的商路，史称「凿空」，丝绸之路正式开辟。",
    same_period: ["同期：罗马正在摧毁迦太基与科林斯"], links: ["汉武帝", "丝绸之路全盛"] },
  { type: "person", name: "斯巴达克斯起义", start: -111, end: -71, factions: ["europe"],
    detail: "罗马共和国晚期最大规模的奴隶起义（前73–前71），被克拉苏与庞培镇压，加速了共和国向帝国的转变。",
    same_period: ["同期：汉武帝晚年（巫蛊之祸前91）；苏拉独裁"], links: ["汉武帝"] },
  { type: "event", name: "罗马从共和国到帝国", start: -49, end: 14, factions: ["europe"],
    detail: "凯撒越过卢比孔河（前49）独裁后被刺（前44），屋大维最终取胜，前27年受尊「奥古斯都」，罗马帝国开始。",
    same_period: ["同期：西汉末年王莽改制（公元9年）；朝鲜半岛高句丽兴起"], links: ["汉武帝", "凯撒"] },
  { type: "person", name: "凯撒", start: -100, end: -44, factions: ["europe"],
    detail: "罗马统帅、政治家，征服高卢，跨卢比孔河引发内战，「我来我见我征服」。遇刺后养子屋大维建立帝制。",
    same_period: ["同期：汉元帝时昭君出塞（前33年）"], links: ["罗马从共和国到帝国"] },
  { type: "person", name: "耶稣", start: -4, end: 30, factions: ["westasia", "europe"],
    detail: "拿撒勒人耶稣在罗马统治的犹太行省传道，后被钉十字架。其门徒建立的基督教最终成为罗马国教并塑造整个西方文明。",
    same_period: ["同期：西汉末年，公元前后王莽建立新朝（9–23）"], links: ["罗马从共和国到帝国"] },
  { type: "event", name: "东汉与佛教东传", start: 25, end: 220, factions: ["china", "india"],
    detail: "光武中兴后东汉发展，明帝时（约67年）佛教正式传入中国（白马寺），蔡伦改进造纸术（105年），班超经营西域。",
    same_period: ["同期：罗马帝国鼎盛（五贤帝时代96–180）；贵霜帝国横跨中亚印度"], links: ["耶稣", "五贤帝"] },
  { type: "person", name: "五贤帝", start: 96, end: 180, factions: ["europe"],
    detail: "涅尔瓦至马可·奥勒留五位皇帝，罗马帝国版图与文明的巅峰，「人类最幸福的时期」（吉本语）。",
    same_period: ["同期：东汉中后期，班超经营西域、党锢之祸"], links: ["东汉与佛教东传"] },
  { type: "event", name: "罗马帝国危机与基督教国教化", start: 235, end: 392, factions: ["europe"],
    detail: "三世纪危机后君士坦丁尼西亚公会议（325），狄奥多西一世定基督教为国教（380），罗马传统多神信仰终结。",
    same_period: ["同期：三国两晋——西晋短暂统一（280）后八王之乱、永嘉之乱（311）"], links: [] },

  /* ===== 中古早期 ===== */
  { type: "event", name: "三国鼎立", start: 220, end: 280, factions: ["china"],
    detail: "曹丕篡汉、刘备孙权相继称帝，赤壁之战（208）后三分格局形成。280年西晋短暂统一。",
    same_period: ["同期：波斯萨珊王朝（224年建立）与罗马持续拉锯"], links: ["罗马帝国危机与基督教国教化"] },
  { type: "event", name: "永嘉之乱与衣冠南渡", start: 311, end: 420, factions: ["china"],
    detail: "匈奴汉赵攻陷洛阳长安，西晋亡，北方进入五胡十六国，晋室南渡建东晋。中国进入近三百年南北对峙期。",
    same_period: ["同期：哥特人渡多瑙河（376）、罗马陷落前夜；笈多王朝在印度兴起（约320）"], links: ["罗马帝国危机与基督教国教化", "笈多王朝"] },
  { type: "event", name: "笈多王朝", start: 320, end: 550, factions: ["india"],
    detail: "印度古典文化黄金时代：梵文文学（迦梨陀娑）、数学（零与十进制成熟）、阿旃陀石窟。",
    same_period: ["同期：东晋南北朝；罗马帝国基督教化并走向分裂"], links: ["永嘉之乱与衣冠南渡"] },
  { type: "event", name: "西罗马帝国灭亡", start: 476, end: 476, factions: ["europe"],
    detail: "日耳曼将领奥多亚克废黜末帝罗慕路斯，西罗马帝国终结，欧洲进入中世纪。",
    same_period: ["同期：南北朝对峙（刘宋、北魏）"], links: ["永嘉之乱与衣冠南渡"] },
  { type: "event", name: "北魏孝文帝改革", start: 471, end: 499, factions: ["china"],
    detail: "迁都洛阳、改汉姓、禁胡语、通婚姻，鲜卑政权全面汉化，为隋唐统一与民族融合奠基。",
    same_period: ["同期：西罗马已亡，东罗马（拜占庭）查士丁尼即将编纂法典"], links: [] },
  { type: "event", name: "查士丁尼与拜占庭", start: 527, end: 565, factions: ["europe"],
    detail: "编纂《民法大全》（罗马法集大成）、建圣索菲亚大教堂、一度收复西地中海。",
    same_period: ["同期：南北朝后期，中国即将走向隋统一"], links: ["北魏孝文帝改革"] },
  { type: "event", name: "隋朝：大运河与科举初创", start: 581, end: 618, factions: ["china"],
    detail: "隋文帝统一南北，炀帝开大运河、创进士科。国祚虽短（37年），但大运河与科举制影响此后1300年。",
    same_period: ["同期：拜占庭与波斯大战两败俱伤，为阿拉伯崛起创造条件"], links: ["唐朝贞观之治"] },
  { type: "event", name: "伊斯兰教兴起与阿拉伯扩张", start: 622, end: 750, factions: ["westasia"],
    detail: "穆罕默德622年迁麦地那（希吉拉历元年起点），此后百年阿拉伯帝国吞并波斯、席卷北非西班牙。",
    same_period: ["同期：中国从隋入唐；西欧法兰克王国宫相掌权"], links: ["唐朝贞观之治"] },
  { type: "event", name: "唐朝贞观之治", start: 627, end: 649, factions: ["china"],
    detail: "唐太宗李世民虚心纳谏、平定东突厥被尊「天可汗」，政治清明国力上升，开启盛唐序幕。",
    same_period: ["同期：阿拉伯帝国正当扩张；日本将开始大化改新（645）"], links: ["伊斯兰教兴起与阿拉伯扩张", "开元盛世", "遣唐使与大化改新"] },
  { type: "event", name: "遣唐使与大化改新", start: 630, end: 894, factions: ["eastasia"],
    detail: "日本派出十余批遣唐使全面学习中国制度文化，645年大化改新仿唐制改革，日本进入律令国家时代。",
    same_period: ["同期：唐朝完备典章制度是日本的范本；新罗统一朝鲜半岛（676）"], links: ["唐朝贞观之治"] },
  { type: "person", name: "李白", start: 701, end: 762, factions: ["china"],
    detail: "盛唐诗人，「诗仙」。浪漫豪放，与杜甫并称李杜，代表作《将进酒》《蜀道难》。",
    same_period: ["同期：阿拉伯帝国倭马亚王朝转向阿拔斯王朝（750）；查理曼帝国即将由法兰克王国演化"], links: ["开元盛世", "杜甫"] },
  { type: "event", name: "开元盛世", start: 713, end: 755, factions: ["china"],
    detail: "唐玄宗前期，中国人口经济文化全面鼎盛，长安人口百万，是世界最大都市。755年安史之乱终结这一盛世。",
    same_period: ["同期：阿拔斯王朝建立，巴格达即将成为世界科学中心"], links: ["李白", "杜甫"] },
  { type: "person", name: "杜甫", start: 712, end: 770, factions: ["china"],
    detail: "「诗圣」，亲历安史之乱，诗史结合，沉郁顿挫，代表作「三吏三别」。",
    same_period: ["同期：欧洲加洛林文艺复兴；阿拉伯帝国阿拔斯革命"], links: ["开元盛世"] },
  { type: "event", name: "查理曼帝国", start: 768, end: 843, factions: ["europe"],
    detail: "查理曼统一西欧大部，800年由教皇加冕称帝。843年《凡尔登条约》三分帝国，形成法德意雏形。",
    same_period: ["同期：唐经安史之乱后藩镇割据；阿拉伯黄金时代正盛"], links: ["开元盛世"] },
  { type: "event", name: "阿拉伯黄金时代", start: 762, end: 1050, factions: ["westasia"],
    detail: "阿拔斯王朝建巴格达「智慧宫」，翻译希腊波斯印度典籍，代数、医学、天文、化学领先世界，造纸术经此地西传。",
    same_period: ["同期：唐朝由盛转衰；加洛林文艺复兴"], links: ["查理曼帝国", "开元盛世"] },

  /* ===== 中古盛期 ===== */
  { type: "event", name: "五代十国与宋朝建立", start: 907, end: 960, factions: ["china"],
    detail: "唐亡后五代十国分裂，960年赵匡胤陈桥兵变建宋，杯酒释兵权重文轻武，开启中国文化最精致的宋代。",
    same_period: ["同期：拜占庭马其顿王朝复兴；神圣罗马帝国即将建立（962）"], links: ["两宋文明"] },
  { type: "event", name: "两宋文明", start: 960, end: 1279, factions: ["china"],
    detail: "活字印刷、火药武器、指南针航海，纸币交子出现，人口过亿。文化上宋词、理学、书院极盛，经济重心南移完成。",
    same_period: ["同期：欧洲中世纪盛期与十字军东征；伊斯兰塞尔柱崛起"], links: ["十字军东征", "活字印刷与四大发明西传"] },
  { type: "event", name: "十字军东征", start: 1096, end: 1291, factions: ["europe", "westasia"],
    detail: "西欧基督教世界对地中海东岸近两百年军事远征，客观上促进了东西方贸易与技术交流。",
    same_period: ["同期：北宋末南宋初；塞尔柱突厥称霸西亚"], links: ["两宋文明"] },
  { type: "event", name: "活字印刷与四大发明西传", start: 1041, end: 1300, factions: ["china"],
    detail: "毕昇发明活字印刷（庆历年间），火药、指南针经阿拉伯传入欧洲，深刻改变世界历史进程。",
    same_period: ["同期：欧洲正处中世纪盛期，大学兴起（博洛尼亚1088）"], links: ["两宋文明", "十字军东征"] },
  { type: "event", name: "成吉思汗与蒙古崛起", start: 1206, end: 1227, factions: ["steppe", "china"],
    detail: "铁木真统一蒙古诸部称成吉思汗，此后蒙古风暴席卷欧亚，建立人类历史上疆域最大的陆地帝国。",
    same_period: ["同期：南宋嘉定年间；第四次十字军攻陷君士坦丁堡（1204）"], links: ["元朝大一统"] },
  { type: "person", name: "马可·波罗", start: 1254, end: 1324, factions: ["europe", "china"],
    detail: "威尼斯旅行家，元世祖时来华十七年，《马可·波罗行纪》激起了欧洲对东方的向往，间接推动大航海。",
    same_period: ["同期：元朝统治中国；欧洲文艺复兴前夜"], links: ["元朝大一统"] },
  { type: "event", name: "元朝大一统", start: 1271, end: 1368, factions: ["china", "steppe"],
    detail: "忽必烈定国号大元，首次由少数民族完成中国大一统，驿站、行省制影响深远；东西方交流空前繁盛。",
    same_period: ["同期：欧洲文艺复兴前夜但丁在世；奥斯曼正在小亚细亚兴起"], links: ["马可·波罗", "成吉思汗与蒙古崛起"] },
  { type: "person", name: "但丁", start: 1265, end: 1321, factions: ["europe"],
    detail: "《神曲》作者，用俗语写成的神学史诗，被视为文艺复兴的精神先驱。",
    same_period: ["同期：元朝前期，马可·波罗在华"], links: ["元朝大一统"] },
  { type: "event", name: "文艺复兴", start: 1350, end: 1600, factions: ["europe"],
    detail: "自意大利发起，复兴古希腊罗马人文精神：达芬奇、米开朗琪罗、拉斐尔；科学、艺术、商业全面勃兴。",
    same_period: ["同期：元末明初，郑和即将七下西洋"], links: ["郑和下西洋", "哥伦布发现新大陆"] },
  { type: "event", name: "明朝建立", start: 1368, end: 1644, factions: ["china"],
    detail: "朱元璋驱逐元朝建明，废丞相、设锦衣卫，专制强化；前期郑和下西洋、后期白银经济与江南市镇繁荣。",
    same_period: ["同期：欧洲文艺复兴与宗教改革；奥斯曼1453年攻陷君士坦丁堡"], links: ["郑和下西洋", "文艺复兴"] },
  { type: "event", name: "奥斯曼帝国崛起", start: 1299, end: 1566, factions: ["westasia"],
    detail: "1453年穆罕默德二世攻陷君士坦丁堡灭拜占庭，苏莱曼大帝时期地跨三洲，阻断传统商路客观上刺激大航海。",
    same_period: ["同期：明朝；欧洲百年战争结束、文艺复兴展开"], links: ["文艺复兴", "明朝建立"] },
  { type: "event", name: "英法百年战争", start: 1337, end: 1453, factions: ["europe"],
    detail: "英法为领地王位断续打了一百余年，圣女贞德扭转战局，战争催生两国民族意识。",
    same_period: ["同期：元末农民战争与明朝建立；黑死病席卷欧亚（1347–1351）"], links: ["明朝建立"] },
  { type: "event", name: "圣女贞德", start: 1412, end: 1431, factions: ["europe"],
    detail: "农家少女自称受神启率军解奥尔良之围，后被俘被英方烧死，1920年封圣。",
    same_period: ["同期：明永乐年间（郑和下西洋）"], links: ["英法百年战争", "郑和下西洋"] },
  { type: "event", name: "郑和下西洋", start: 1405, end: 1433, factions: ["china"],
    detail: "七下西洋最远抵达东非，宝船船队两万余人，比哥伦布早近九十年，但未形成持续殖民贸易体系。",
    same_period: ["同期：葡萄牙开始沿非洲西岸探航，为绕过好望角做准备"], links: ["明朝建立", "哥伦布发现新大陆"] },
  { type: "event", name: "哥伦布发现新大陆", start: 1492, end: 1504, factions: ["europe", "americas"],
    detail: "哥伦布在西班牙资助下横渡大西洋抵达美洲，开启「大航海时代」与哥伦布大交换，也开启了美洲原住民的浩劫。",
    same_period: ["同期：明朝弘治年间；葡萄牙达伽马1498年绕好望角抵印度"], links: ["郑和下西洋", "文艺复兴"] },
  { type: "event", name: "宗教改革", start: 1517, end: 1648, factions: ["europe"],
    detail: "路德《九十五条论纲》引发，新教诞生，欧洲宗教版图重划，三十年战争（1618–1648）后《威斯特伐利亚和约》确立主权国家体系。",
    same_period: ["同期：明朝中后期（嘉靖万历），戚继光抗倭、张居正改革"], links: ["文艺复兴", "明朝建立"] },
  { type: "person", name: "达芬奇", start: 1452, end: 1519, factions: ["europe"],
    detail: "文艺复兴全才：画家（《蒙娜丽莎》《最后的晚餐》）、解剖学家、工程师，代表「文艺复兴人」理想。",
    same_period: ["同期：明朝成化至正德年间；奥斯曼苏莱曼大帝即将登基"], links: ["文艺复兴"] },
  { type: "person", name: "米开朗琪罗", start: 1475, end: 1564, factions: ["europe"],
    detail: "雕塑家画家建筑师，《大卫》《西斯廷天顶画》《圣殇》传世，与达芬奇拉斐尔并称文艺复兴三杰。",
    same_period: ["同期：明朝弘治至嘉靖；马丁·路德1517年发起宗教改革"], links: ["宗教改革"] },
  { type: "event", name: "哥白尼革命", start: 1543, end: 1687, factions: ["europe"],
    detail: "1543年哥白尼《天体运行论》提出日心说，经伽利略、开普勒到牛顿《自然哲学的数学原理》（1687），现代科学体系建立。",
    same_period: ["同期：明朝嘉靖至康熙前期；奥斯曼苏莱曼大帝时代"], links: ["宗教改革", "文艺复兴"] },
  { type: "event", name: "阿兹特克帝国", start: 1428, end: 1521, factions: ["americas"],
    detail: "中美洲军事帝国，都城特诺奇蒂特兰人口二十余万，1521年被西班牙科尔特斯联合原住民攻灭。",
    same_period: ["同期：明朝中期；欧洲文艺复兴鼎盛"], links: ["哥伦布发现新大陆"] },
  { type: "event", name: "印加帝国", start: 1438, end: 1533, factions: ["americas"],
    detail: "南美最大原住民帝国，以马丘比丘与山巅道路网著称，1533年被皮萨罗征服。",
    same_period: ["同期：明朝中期；欧洲宗教改革进行中"], links: ["哥伦布发现新大陆"] },

  /* ===== 革命世纪 ===== */
  { type: "event", name: "康乾盛世", start: 1661, end: 1796, factions: ["china"],
    detail: "康熙、雍正、乾隆三帝，平定三藩、收台湾、定准噶尔，奠定现代中国疆域版图；人口破三亿，但闭关与文字狱埋下落后伏笔。",
    same_period: ["同期：英国工业革命酝酿、美国独立（1776）、法国大革命（1789）——西方剧变正对应清代中期"], links: ["工业革命", "美国独立战争", "法国大革命"] },
  { type: "event", name: "美国独立战争", start: 1775, end: 1783, factions: ["americas", "europe"],
    detail: "十三州脱离英国独立，《独立宣言》宣告「人人生而平等」，1787年宪法建立联邦共和制，现代民主共和国的起点之一。",
    same_period: ["同期：清朝乾隆四十年前后；欧洲启蒙运动尾声"], links: ["法国大革命", "康乾盛世"] },
  { type: "event", name: "法国大革命", start: 1789, end: 1799, factions: ["europe"],
    detail: "攻占巴士底狱、《人权宣言》、处死路易十六、拿破仑崛起——现代政治左中右光谱、民族国家与公民观念由此发端。",
    same_period: ["同期：清朝乾隆晚年，白莲教起义酝酿"], links: ["拿破仑时代", "康乾盛世"] },
  { type: "person", name: "拿破仑", start: 1769, end: 1821, factions: ["europe"],
    detail: "从炮兵军官到法兰西皇帝，《拿破仑法典》影响大陆法系至今，兵败滑铁卢（1815）后流放圣赫勒拿。",
    same_period: ["同期：清朝嘉庆年间，白莲教起义（1796–1804）"], links: ["法国大革命"] },
  { type: "event", name: "拿破仑时代", start: 1799, end: 1815, factions: ["europe"],
    detail: "拿破仑执政至滑铁卢战败，横扫欧洲传播法国大革命理念，也刺激各国民族主义觉醒。",
    same_period: ["同期：清朝嘉庆年间"], links: ["拿破仑", "法国大革命"] },
  { type: "event", name: "工业革命", start: 1760, end: 1840, factions: ["europe"],
    detail: "瓦特改良蒸汽机（1776）、珍妮纺纱机、铁路汽船相继出现，人类从农业文明跃入工业文明，西方与东方实力对比彻底逆转。",
    same_period: ["同期：清朝乾隆至道光——正是「康乾盛世」与鸦片战争之间"], links: ["鸦片战争", "康乾盛世"] },
  { type: "event", name: "鸦片战争", start: 1840, end: 1842, factions: ["china", "europe"],
    detail: "英国为打开中国市场发动战争，清廷战败签《南京条约》，割香港岛、五口通商——中国近代史开端，进入半殖民地深渊。",
    same_period: ["同期：英国工业革命完成；美国西进运动；《共产党宣言》1848年发表"], links: ["工业革命", "太平天国"] },
  { type: "event", name: "太平天国", start: 1851, end: 1864, factions: ["china"],
    detail: "洪秀全以拜上帝会起事，定都南京，是19世纪世界最大规模内战，死亡人数以千万计，沉重打击清廷。",
    same_period: ["同期：克里米亚战争（1853–1856）、美国内战（1861–1865）、日本开港（1853）"], links: ["鸦片战争"] },
  { type: "event", name: "明治维新", start: 1868, end: 1890, factions: ["eastasia"],
    detail: "日本明治政府「富国强兵、殖产兴业、文明开化」，三十年内完成近代化，成为亚洲第一个工业化国家，也走上对外扩张之路。",
    same_period: ["同期：清朝洋务运动（1861–1895）；意大利德国统一；美国南北战争后重建"], links: ["洋务运动"] },
  { type: "event", name: "洋务运动", start: 1861, end: 1895, factions: ["china"],
    detail: "曾国藩李鸿章张之洞等「师夷长技以自强」，办江南制造局、福州船政局、北洋水师；甲午战败标志其失败。",
    same_period: ["同期：明治维新、德国意大利统一、第二次工业革命"], links: ["明治维新", "甲午战争"] },
  { type: "event", name: "德国统一", start: 1871, end: 1871, factions: ["europe"],
    detail: "俾斯麦通过三场王朝战争统一德意志，普鲁士威廉一世在凡尔赛镜厅加冕称帝，欧洲均势从此改变。",
    same_period: ["同期：清朝同治中兴、洋务运动进行中"], links: ["洋务运动"] },
  { type: "event", name: "甲午战争", start: 1894, end: 1895, factions: ["china", "eastasia"],
    detail: "清日为朝鲜主权开战，北洋水师全军覆没，《马关条约》割台湾赔二亿两，中国民族危机空前，戊戌变法由此激发。",
    same_period: ["同期：日本明治维新成功检验；欧洲列强瓜分非洲（柏林会议后）"], links: ["洋务运动", "戊戌变法", "明治维新"] },
  { type: "event", name: "戊戌变法", start: 1898, end: 1898, factions: ["china"],
    detail: "光绪帝任用康有为梁启超百日维新，被慈禧政变扼杀，六君子被杀——改良之路受挫，革命思潮兴起。",
    same_period: ["同期：美国美西战争、居里夫人发现镭"], links: ["甲午战争", "辛亥革命"] },
  { type: "event", name: "义和团与八国联军", start: 1899, end: 1901, factions: ["china", "europe"],
    detail: "义和团运动引发八国联军侵华，《辛丑条约》赔款四亿五千万两，清廷沦为列强工具，十年后覆亡。",
    same_period: ["同期：维多利亚时代末期；第二次工业革命电气化"], links: ["戊戌变法", "辛亥革命"] },
  { type: "event", name: "辛亥革命", start: 1911, end: 1912, factions: ["china"],
    detail: "武昌起义爆发，各省响应，1912年中华民国成立、清帝退位，两千余年帝制终结。",
    same_period: ["同期：欧洲协约国与同盟国对峙，大战一触即发"], links: ["第一次世界大战", "戊戌变法"] },
  { type: "event", name: "第一次世界大战", start: 1914, end: 1918, factions: ["europe", "westasia"],
    detail: "萨拉热窝事件引爆，四大帝国解体（德奥俄土），凡尔赛体系重塑世界，伤亡三千余万。",
    same_period: ["同期：民国初年军阀混战；新文化运动（1915–）兴起"], links: ["辛亥革命", "新文化运动"] },
  { type: "event", name: "新文化运动", start: 1915, end: 1923, factions: ["china"],
    detail: "陈独秀《新青年》、胡适白话文、德先生赛先生，中国思想界激进启蒙，五四运动（1919）将其推向高潮。",
    same_period: ["同期：一战与俄国十月革命（1917）"], links: ["第一次世界大战", "俄国革命"] },
  { type: "event", name: "俄国革命", start: 1917, end: 1923, factions: ["europe"],
    detail: "二月革命推翻沙皇，十月革命布尔什维克夺权，建立人类第一个社会主义国家苏联。",
    same_period: ["同期：中国新文化运动与军阀时代"], links: ["新文化运动", "第一次世界大战"] },
  { type: "event", name: "第二次世界大战", start: 1939, end: 1945, factions: ["europe", "westasia", "americas"],
    detail: "德国闪击波兰开战，全球六十年余国卷入，死伤过亿；1945年广岛长崎原子弹、联合国成立，战后国际秩序建立。",
    same_period: ["同期：中国抗日战争（1937–1945）是二战东方主战场"], links: ["抗日战争", "第一次世界大战"] },
  { type: "event", name: "抗日战争", start: 1937, end: 1945, factions: ["china"],
    detail: "卢沟桥事变后中国全面抗战八年（自1931九一八则十四年），付出三千五百万军民伤亡，1945年日本投降。",
    same_period: ["同期：欧洲战场、太平洋战场；大西洋宪章与联合国筹建"], links: ["第二次世界大战", "新文化运动"] },
  { type: "person", name: "爱因斯坦", start: 1879, end: 1955, factions: ["europe", "americas"],
    detail: "相对论创立者，1905奇迹年五篇论文改写物理学，1921年诺贝尔奖，晚年呼吁和平反对核武。",
    same_period: ["同期：清末民初，辛亥革命至新文化运动"], links: ["第二次世界大战", "戊戌变法"] },
  { type: "person", name: "鲁迅", start: 1881, end: 1936, factions: ["china"],
    detail: "中国现代文学奠基人，《狂人日记》《阿Q正传》批判国民性，新文化运动主将。",
    same_period: ["同期：欧洲现代主义文学艺术鼎盛"], links: ["新文化运动"] },

  /* ===== 当代 ===== */
  { type: "event", name: "中华人民共和国成立", start: 1949, end: 1949, factions: ["china"],
    detail: "中国共产党在内战中获胜，10月1日中华人民共和国成立，中国历史翻开新页。",
    same_period: ["同期：北约成立、苏联原子弹试爆、冷战格局成型"], links: ["第二次世界大战"] },
  { type: "event", name: "冷战", start: 1947, end: 1991, factions: ["europe", "westasia", "americas"],
    detail: "美苏两大阵营近半个世纪全面对抗：柏林危机、古巴导弹危机、太空竞赛、代理人战争，1991年苏联解体终结。",
    same_period: ["同期：新中国建设与改革开放；亚非拉去殖民化浪潮"], links: ["中华人民共和国成立", "改革开放"] },
  { type: "event", name: "去殖民化浪潮", start: 1947, end: 1975, factions: ["africa", "india", "westasia"],
    detail: "印巴分治（1947）开始，加纳（1957）带动非洲独立潮，六十年代数十个新国家诞生，世界政治地图重绘。",
    same_period: ["同期：冷战高峰；新中国倡导万隆会议（1955）"], links: ["冷战"] },
  { type: "event", name: "改革开放", start: 1978, end: 2000, factions: ["china"],
    detail: "十一届三中全会后中国经济体制改革与对外开放，四十年间成为世界第二大经济体，数亿人脱贫。",
    same_period: ["同期：信息技术革命、苏联解体、全球化加速"], links: ["冷战", "中华人民共和国成立"] },
  { type: "event", name: "信息技术革命", start: 1971, end: 2000, factions: ["americas", "europe"],
    detail: "英特尔微处理器（1971）、个人电脑、互联网（1969–1991万维网）相继出现，人类进入信息时代。",
    same_period: ["同期：改革开放；冷战终结"], links: ["改革开放", "冷战"] },
  { type: "event", name: "人类登月", start: 1969, end: 1969, factions: ["americas"],
    detail: "阿波罗11号宇航员阿姆斯特朗踏上月球，「这是个人的一小步，却是人类的一大步」。",
    same_period: ["同期：文革中期；越战正酣"], links: ["冷战"] },
];

/* 索引：按 name 快速查找 */
const ITEM_INDEX = {};
ITEMS.forEach(it => { ITEM_INDEX[it.name] = it; });

/* =====================================================================
 * P1 扩充：朝代细化 / 科技艺术 / 全球史补齐
 * ===================================================================== */
ITEMS.push(
  /* ---- 中国史细化 ---- */
  { type: "event", name: "安史之乱", start: 755, end: 763, factions: ["china"],
    detail: "安禄山、史思明叛乱八年，人口锐减、藩镇割据成型，是唐朝乃至整个中国中古史的转折点：盛唐气象终结，经济重心开始南移。",
    same_period: ["同期：阿拉伯阿拔斯王朝正处鼎盛，巴格达成为世界科学中心；加洛林王朝丕献三世献土教皇"], links: ["开元盛世", "杜甫"] },
  { type: "event", name: "靖康之变与南宋偏安", start: 1127, end: 1141, factions: ["china"],
    detail: "金兵攻破开封掳徽钦二帝，北宋亡。宋室南渡临安（杭州），偏安江南150余年，江南由此彻底成为中国经济文化中心。",
    same_period: ["同期：欧洲第二次十字军东征（1147）；罗曼式建筑向哥特式过渡"], links: ["两宋文明"] },
  { type: "event", name: "王安石变法", start: 1069, end: 1085, factions: ["china"],
    detail: "宋神宗任用王安石推行青苗法、募役法、市易法等，试图富国强兵。因触动官僚地主利益与执行走样而失败，新旧党争此后撕裂北宋政坛。",
    same_period: ["同期：诺曼征服英格兰（1066）刚过去不久；塞尔柱突厥击败拜占庭（曼齐刻尔特1071）"], links: ["两宋文明"] },
  { type: "event", name: "郑成功收复台湾", start: 1661, end: 1662, factions: ["china"],
    detail: "郑成功率军围攻热兰遮城九个月，驱逐荷兰东印度公司势力，收复台湾。这是东方国家早期反抗欧洲殖民扩张的标志性胜利。",
    same_period: ["同期：康熙帝即位（1661）；英国斯图亚特复辟；路易十四亲政"], links: ["康乾盛世"] },
  { type: "event", name: "文景之治后的七国之乱", start: -154, end: -154, factions: ["china"],
    detail: "吴王刘濞联合七国以「清君侧」名义叛乱，三个月即被周亚夫平定。此后诸侯王势力大衰，中央集权强化，为汉武帝大一统铺路。",
    same_period: ["同期：罗马正在毁灭迦太基（前146），地中海霸权确立"], links: ["汉武帝"] },
  { type: "event", name: "黄巢起义与唐朝崩溃", start: 875, end: 884, factions: ["china"],
    detail: "盐商黄巢率流动作战大军转战大半个中国，攻入长安，摧毁了唐王朝的统治根基。此后中国进入五代十国大分裂。",
    same_period: ["同期：拜占庭马其顿王朝中兴；维京人在北欧-不列颠扩张"], links: ["五代十国与宋朝建立"] },
  { type: "event", name: "土木堡之变", start: 1449, end: 1449, factions: ["china"],
    detail: "明英宗亲征瓦剌，五十万大军在土木堡覆没，皇帝被俘，明朝由盛转衰。于谦主导北京保卫战力挽狂澜。",
    same_period: ["同期：欧洲百年战争刚结束（1453年君士坦丁堡也即将陷落）"], links: ["明朝建立"] },

  /* ---- 科技与艺术 ---- */
  { type: "event", name: "都江堰建成", start: -256, end: -251, factions: ["china"],
    detail: "蜀郡太守李冰父子主持修建的无坝引水工程，使成都平原成为「天府之国」，运行2200余年至今仍在灌溉，是世界水利史奇迹。",
    same_period: ["同期：罗马与迦太基第一次布匿战争尾声"], links: ["秦始皇统一中国"] },
  { type: "event", name: "张衡地动仪与浑天仪", start: 132, end: 132, factions: ["china"],
    detail: "东汉科学家张衡制候风地动仪（测地震方位）与浑天仪（天象演示），并有《二京赋》等文学成就，是古代罕见的百科式科学家。",
    same_period: ["同期：罗马五贤帝时代（哈德良在位）"], links: ["东汉与佛教东传", "五贤帝"] },
  { type: "event", name: "祖冲之与圆周率", start: 480, end: 500, factions: ["china"],
    detail: "南北朝数学家祖冲之将圆周率精确到小数点后七位（3.1415926–3.1415927），领先世界约900年；其子祖暅之提出等积原理。",
    same_period: ["同期：西罗马已亡，拜占庭查士丁尼时代前夜；笈多王朝数学同样辉煌（阿耶波多）"], links: ["北魏孝文帝改革"] },
  { type: "event", name: "敦煌莫高窟开凿", start: 366, end: 1368, factions: ["china", "westasia"],
    detail: "自前秦乐僔开窟起持续营造千年，现存洞窟735个、壁画4.5万平方米，是丝绸之路佛教艺术的活化石。",
    same_period: ["跨千年营造：见证五胡十六国至元代的东西方艺术交流"], links: ["永嘉之乱与衣冠南渡"] },
  { type: "event", name: "《清明上河图》与汴京繁华", start: 1100, end: 1125, factions: ["china"],
    detail: "张择端绘北宋汴京市井长卷：5米多长画卷含800余人物，是宋代商业革命与城市文明的直观见证。",
    same_period: ["同期：欧洲中世纪城市复兴、哥特式教堂开始兴建（圣但尼1144）"], links: ["两宋文明"] },
  { type: "event", name: "古腾堡印刷术", start: 1440, end: 1455, factions: ["europe"],
    detail: "古腾堡金属活字印刷机投产，《四十二行圣经》印成。书价骤降，识字率飙升，被称为「改变世界的机器」，宗教改革因它而燎原。",
    same_period: ["同期：明朝正统年间；欧洲百年战争尾声"], links: ["宗教改革", "文艺复兴"] },
  { type: "event", name: "帕特农神庙", start: -447, end: -432, factions: ["europe"],
    detail: "伯里克利时代的雅典在卫城兴建帕特农神庙，多立克式建筑的巅峰，见证了雅典民主与古典文明的黄金期。",
    same_period: ["同期：战国初期魏文侯变法（李悝、西门豹治邺）"], links: ["希波战争", "苏格拉底"] },
  { type: "event", name: "吴哥窟", start: 1113, end: 1150, factions: ["eastasia"],
    detail: "高棉帝国苏耶跋摩二世兴建的世界最大宗教建筑群，融合印度教与佛教艺术，是东南亚古典文明的巅峰代表。",
    same_period: ["同期：南宋建立（1127）；欧洲哥特式建筑兴起"], links: ["靖康之变与南宋偏安"] },
  { type: "event", name: "巴赫与欧洲巴洛克音乐", start: 1700, end: 1750, factions: ["europe"],
    detail: "巴赫、亨德尔将复调音乐推向顶峰。巴洛克艺术（贝尼尼雕塑、凡尔赛宫）代表绝对君主时代的审美极致。",
    same_period: ["同期：清朝康熙中后期（平三藩、收台湾、雅克萨之战）"], links: ["康乾盛世"] },

  /* ---- 经济与贸易 ---- */
  { type: "event", name: "丝绸之路全盛", start: -100, end: 200, factions: ["china", "westasia", "steppe"],
    detail: "汉朝与罗马（大秦）分别控制东西两端，甘英出使、罗马商人抵汉（166年有记载），丝绸、香料、玻璃、佛教艺术沿路流动。",
    same_period: ["同期：罗马帝国鼎盛（五贤帝）；贵霜帝国控制中亚商路"], links: ["张骞通西域", "五贤帝"] },
  { type: "event", name: "宋钱与海洋贸易时代", start: 1000, end: 1300, factions: ["china", "eastasia"],
    detail: "宋代铜钱成为东亚东南亚「国际货币」，泉州、广州设市舶司，海上丝绸之路取代陆路成为主要通道，刺桐港（泉州）为世界大港。",
    same_period: ["同期：威尼斯热那亚垄断地中海贸易；十字军国家与意大利城邦繁荣"], links: ["两宋文明", "十字军东征"] },
  { type: "event", name: "荷兰东印度公司与商业革命", start: 1602, end: 1700, factions: ["europe"],
    detail: "世界第一家股份制公司（VOC）成立，发明股票交易所与近代金融体系。荷兰「海上马车夫」垄断东方贸易，商业革命催生资本主义。",
    same_period: ["同期：明朝万历年间（张居正改革后），白银大量流入中国"], links: ["明朝建立", "工业革命"] },

  /* ---- 美洲补齐 ---- */
  { type: "event", name: "玛雅文明古典期", start: 250, end: 900, factions: ["americas"],
    detail: "玛雅城邦（蒂卡尔、帕伦克）鼎盛：独立发明文字、精确历法、「零」概念、巨型金字塔。900年前后神秘衰落。",
    same_period: ["同期：中国从三国到唐末；罗马帝国衰亡与拜占庭兴起"], links: ["三国鼎立", "唐朝贞观之治"] },
  { type: "event", name: "美国内战", start: 1861, end: 1865, factions: ["americas"],
    detail: "南北战争：林肯领导北方战胜蓄奴南方，废除奴隶制（1863《解放宣言》），美国从此走上工业强国的快车道。",
    same_period: ["同期：清朝太平天国覆灭（1864）、洋务运动开启"], links: ["太平天国", "洋务运动"] },
  { type: "event", name: "阿拉斯加购地案", start: 1867, end: 1867, factions: ["americas", "europe"],
    detail: "美国以720万美元从俄国购得阿拉斯加（每英亩约2美分），当时被讥为「西沃德的冰箱」，后因金矿与战略价值证明是史上最划算交易之一。",
    same_period: ["同期：日本明治维新前夜（1868）、德意志统一前夜"], links: ["明治维新", "德国统一"] },

  /* ---- 非洲补齐 ---- */
  { type: "event", name: "加纳帝国（西非）", start: 700, end: 1240, factions: ["africa"],
    detail: "西非第一个大帝国，控盐金贸易（撒哈拉商道枢纽），阿拉伯文献称其「黄金之国」，1240年被马里帝国吞并。",
    same_period: ["同期：唐朝至南宋；阿拉伯帝国鼎盛"], links: ["阿拉伯黄金时代", "两宋文明"] },
  { type: "event", name: "马里帝国与曼萨·穆萨", start: 1235, end: 1400, factions: ["africa"],
    detail: "曼萨·穆萨1324年朝觐麦加时挥金如土，导致开罗金价贬值十余年，被称为「史上最富有的人」。廷巴克图成为伊斯兰学术中心。",
    same_period: ["同期：元朝中期；欧洲文艺复兴前夜"], links: ["元朝大一统"] },
  { type: "event", name: "大津巴布韦", start: 1100, end: 1450, factions: ["africa"],
    detail: "南部非洲绍纳人建成的石头城遗址（占地7平方公里），是非洲内陆铁器时代文明的杰作，靠象牙黄金贸易繁荣。",
    same_period: ["同期：南宋至明初（郑和船队或曾抵达东非）"], links: ["郑和下西洋"] },
  { type: "event", name: "奴隶贸易与三角航路", start: 1500, end: 1860, factions: ["africa", "americas", "europe"],
    detail: "约360年跨大西洋奴隶贸易，超过1200万非洲人被贩运至美洲，是近代早期最大规模强制人口迁移，深刻塑造了美洲与非洲的社会。",
    same_period: ["同期：明清时期；欧洲殖民扩张"], links: ["哥伦布发现新大陆", "美国内战"] },

  /* ---- 东南亚与西亚补齐 ---- */
  { type: "event", name: "室利佛逝与海上东南亚", start: 670, end: 1300, factions: ["eastasia"],
    detail: "苏门答腊的室利佛逝（三佛齐）控制马六甲海峡数百年，是佛教学术中心（义净曾驻留），中国、印度、阿拉伯贸易的中转站。",
    same_period: ["同期：唐至元；阿拉伯商网络遍及印度洋"], links: ["唐朝贞观之治", "宋钱与海洋贸易时代"] },
  { type: "event", name: "萨珊波斯", start: 224, end: 651, factions: ["westasia"],
    detail: "波斯第二帝国，与罗马-拜占庭缠斗四百年，祆教国教化，银币流通欧亚，651年被阿拉伯帝国灭。",
    same_period: ["同期：三国至唐初；拜占庭希拉克略王朝"], links: ["三国鼎立", "伊斯兰教兴起与阿拉伯扩张"] },
  { type: "event", name: "塞尔柱突厥与曼齐刻尔特", start: 1055, end: 1194, factions: ["westasia", "steppe"],
    detail: "突厥人入主巴格达建立塞尔柱帝国，1071年曼齐刻尔特之战大败拜占庭，小亚细亚逐渐突厥化，为奥斯曼崛起埋下伏笔。",
    same_period: ["同期：北宋王安石变法；欧洲十字军东征（征召的直接诱因）"], links: ["王安石变法", "十字军东征"] },
  { type: "event", name: "奥斯曼帝国衰落与「欧洲病夫」", start: 1700, end: 1922, factions: ["westasia"],
    detail: "奥斯曼从维也纳城下败退（1683）后逐渐衰落，被列强称「欧洲病夫」，一战站错队后1922年帝国终结，凯末尔建立土耳其共和国。",
    same_period: ["同期：清朝由盛转衰；欧洲工业革命与帝国主义扩张"], links: ["康乾盛世", "工业革命"] },

  /* ---- 时间感校准条目 ---- */
  { type: "event", name: "牛津大学与阿兹特克帝国的年代对照", start: 1096, end: 1428, factions: ["europe", "americas"],
    detail: "牛津大学于1096年已有教学记录，而阿兹特克帝国建立于1428年，两者相差三百三十余年。类似地：清德宗光绪帝与美国总统林肯是同时代人（均活跃于1860年代）；埃及吉萨金字塔建成时，弗兰格尔岛上的最后一群猛犸象尚存（约公元前1700年才灭绝）。这类对照有助于校准对历史时间尺度的直觉。",
    same_period: ["对历史时间尺度感到意外，正说明需要以对照的方式理解历史——可在本图谱中自行验证上述年代关系"], links: ["十字军东征", "阿兹特克帝国"] }
);
ITEMS.forEach(it => { if (!ITEM_INDEX[it.name]) ITEM_INDEX[it.name] = it; });
